package DataBase_AutoGenerated;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Objects;

@Entity
public class Atrybuty {
    private int idAtrybuty;
    private String imgPath;
    private String chipset;
    private String socket;
    private String liczbaRdzeni;
    private String liczbaWatkow;
    private String czestotliwoscProcesoraMin;
    private String czestotliwoscProcesoraMax;
    private String czestotliwoscMhz;
    private String zasilanie;
    private String dlugosc;
    private String szerokosc;
    private String wysokosc;
    private String glebokosc;
    private String moc;
    private String rodzaj;
    private String cale;
    private String iloscRamGb;
    private String zlacza;
    private String szynaDanychBit;
    private String interfejs;
    private String formatDysku;
    private String pojemnoscGb;
    private String obroty;
    private String szybkoscOdczytu;
    private String szybkoscZapisu;
    private String standardPamieci;
    private String iloscSlotowPamieci;
    private String czestotliwoscPamieciMax;
    private String iloscPamieciMax;
    private String modularneOkablowanie;
    private String certyfikatSprawnosci;
    private String napiecie;
    private String chlodzenie;
    private String opoznienie;
    private String liczbaModulow;
    private String kompatybilnosc;
    private String maxDlugoscGpu;
    private String maxWysokoscChlodzeniaCpu;
    private String waga;
    private String poziomHalasu;
    private String iloscWentylatorow;
    private String sposobMontazu;
    private String procesor;
    private String kartaGraficzna;
    private String systemOperacyjny;
    private String bateria;
    private String zastosowanie;
    private String liczbaStanowisk;
    private String okresLicencji;
    private String platforma;
    private String skladPakietu;
    private String architektura;
    private String licencja;
    private String technologiaDruku;
    private String maxFormatPapieru;
    private String podajnikPapieru;
    private String odbiornikPapieru;
    private String szybkoscDruku;
    private String maxRozdzielczoscDruku;
    private String lacznosc;
    private String rozdzielczosc;
    private String formatEkranu;
    private String odswiezanieEkranu;
    private String matryca;
    private String dlugoscPrzewoduZasieg;

    @Id
    @Column(name = "idAtrybuty")
    public int getIdAtrybuty() {
        return idAtrybuty;
    }

    public void setIdAtrybuty(int idAtrybuty) {
        this.idAtrybuty = idAtrybuty;
    }

    @Basic
    @Column(name = "img_path")
    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    @Basic
    @Column(name = "chipset")
    public String getChipset() {
        return chipset;
    }

    public void setChipset(String chipset) {
        this.chipset = chipset;
    }

    @Basic
    @Column(name = "socket")
    public String getSocket() {
        return socket;
    }

    public void setSocket(String socket) {
        this.socket = socket;
    }

    @Basic
    @Column(name = "liczba_rdzeni")
    public String getLiczbaRdzeni() {
        return liczbaRdzeni;
    }

    public void setLiczbaRdzeni(String liczbaRdzeni) {
        this.liczbaRdzeni = liczbaRdzeni;
    }

    @Basic
    @Column(name = "liczba_watkow")
    public String getLiczbaWatkow() {
        return liczbaWatkow;
    }

    public void setLiczbaWatkow(String liczbaWatkow) {
        this.liczbaWatkow = liczbaWatkow;
    }

    @Basic
    @Column(name = "czestotliwosc_procesora_min")
    public String getCzestotliwoscProcesoraMin() {
        return czestotliwoscProcesoraMin;
    }

    public void setCzestotliwoscProcesoraMin(String czestotliwoscProcesoraMin) {
        this.czestotliwoscProcesoraMin = czestotliwoscProcesoraMin;
    }

    @Basic
    @Column(name = "czestotliwosc_procesora_max")
    public String getCzestotliwoscProcesoraMax() {
        return czestotliwoscProcesoraMax;
    }

    public void setCzestotliwoscProcesoraMax(String czestotliwoscProcesoraMax) {
        this.czestotliwoscProcesoraMax = czestotliwoscProcesoraMax;
    }

    @Basic
    @Column(name = "czestotliwosc_Mhz")
    public String getCzestotliwoscMhz() {
        return czestotliwoscMhz;
    }

    public void setCzestotliwoscMhz(String czestotliwoscMhz) {
        this.czestotliwoscMhz = czestotliwoscMhz;
    }

    @Basic
    @Column(name = "Zasilanie")
    public String getZasilanie() {
        return zasilanie;
    }

    public void setZasilanie(String zasilanie) {
        this.zasilanie = zasilanie;
    }

    @Basic
    @Column(name = "Dlugosc")
    public String getDlugosc() {
        return dlugosc;
    }

    public void setDlugosc(String dlugosc) {
        this.dlugosc = dlugosc;
    }

    @Basic
    @Column(name = "szerokosc")
    public String getSzerokosc() {
        return szerokosc;
    }

    public void setSzerokosc(String szerokosc) {
        this.szerokosc = szerokosc;
    }

    @Basic
    @Column(name = "wysokosc")
    public String getWysokosc() {
        return wysokosc;
    }

    public void setWysokosc(String wysokosc) {
        this.wysokosc = wysokosc;
    }

    @Basic
    @Column(name = "glebokosc")
    public String getGlebokosc() {
        return glebokosc;
    }

    public void setGlebokosc(String glebokosc) {
        this.glebokosc = glebokosc;
    }

    @Basic
    @Column(name = "moc")
    public String getMoc() {
        return moc;
    }

    public void setMoc(String moc) {
        this.moc = moc;
    }

    @Basic
    @Column(name = "rodzaj")
    public String getRodzaj() {
        return rodzaj;
    }

    public void setRodzaj(String rodzaj) {
        this.rodzaj = rodzaj;
    }

    @Basic
    @Column(name = "Cale")
    public String getCale() {
        return cale;
    }

    public void setCale(String cale) {
        this.cale = cale;
    }

    @Basic
    @Column(name = "ilosc_RAM_GB")
    public String getIloscRamGb() {
        return iloscRamGb;
    }

    public void setIloscRamGb(String iloscRamGb) {
        this.iloscRamGb = iloscRamGb;
    }

    @Basic
    @Column(name = "zlacza")
    public String getZlacza() {
        return zlacza;
    }

    public void setZlacza(String zlacza) {
        this.zlacza = zlacza;
    }

    @Basic
    @Column(name = "szyna_danych_bit")
    public String getSzynaDanychBit() {
        return szynaDanychBit;
    }

    public void setSzynaDanychBit(String szynaDanychBit) {
        this.szynaDanychBit = szynaDanychBit;
    }

    @Basic
    @Column(name = "interfejs")
    public String getInterfejs() {
        return interfejs;
    }

    public void setInterfejs(String interfejs) {
        this.interfejs = interfejs;
    }

    @Basic
    @Column(name = "format_dysku")
    public String getFormatDysku() {
        return formatDysku;
    }

    public void setFormatDysku(String formatDysku) {
        this.formatDysku = formatDysku;
    }

    @Basic
    @Column(name = "pojemnosc_GB")
    public String getPojemnoscGb() {
        return pojemnoscGb;
    }

    public void setPojemnoscGb(String pojemnoscGb) {
        this.pojemnoscGb = pojemnoscGb;
    }

    @Basic
    @Column(name = "obroty")
    public String getObroty() {
        return obroty;
    }

    public void setObroty(String obroty) {
        this.obroty = obroty;
    }

    @Basic
    @Column(name = "szybkosc_odczytu")
    public String getSzybkoscOdczytu() {
        return szybkoscOdczytu;
    }

    public void setSzybkoscOdczytu(String szybkoscOdczytu) {
        this.szybkoscOdczytu = szybkoscOdczytu;
    }

    @Basic
    @Column(name = "szybkosc_zapisu")
    public String getSzybkoscZapisu() {
        return szybkoscZapisu;
    }

    public void setSzybkoscZapisu(String szybkoscZapisu) {
        this.szybkoscZapisu = szybkoscZapisu;
    }

    @Basic
    @Column(name = "standard_pamieci")
    public String getStandardPamieci() {
        return standardPamieci;
    }

    public void setStandardPamieci(String standardPamieci) {
        this.standardPamieci = standardPamieci;
    }

    @Basic
    @Column(name = "ilosc_slotow_pamieci")
    public String getIloscSlotowPamieci() {
        return iloscSlotowPamieci;
    }

    public void setIloscSlotowPamieci(String iloscSlotowPamieci) {
        this.iloscSlotowPamieci = iloscSlotowPamieci;
    }

    @Basic
    @Column(name = "czestotliwosc_pamieci_max")
    public String getCzestotliwoscPamieciMax() {
        return czestotliwoscPamieciMax;
    }

    public void setCzestotliwoscPamieciMax(String czestotliwoscPamieciMax) {
        this.czestotliwoscPamieciMax = czestotliwoscPamieciMax;
    }

    @Basic
    @Column(name = "ilosc_pamieci_max")
    public String getIloscPamieciMax() {
        return iloscPamieciMax;
    }

    public void setIloscPamieciMax(String iloscPamieciMax) {
        this.iloscPamieciMax = iloscPamieciMax;
    }

    @Basic
    @Column(name = "modularne_okablowanie")
    public String getModularneOkablowanie() {
        return modularneOkablowanie;
    }

    public void setModularneOkablowanie(String modularneOkablowanie) {
        this.modularneOkablowanie = modularneOkablowanie;
    }

    @Basic
    @Column(name = "certyfikat_sprawnosci")
    public String getCertyfikatSprawnosci() {
        return certyfikatSprawnosci;
    }

    public void setCertyfikatSprawnosci(String certyfikatSprawnosci) {
        this.certyfikatSprawnosci = certyfikatSprawnosci;
    }

    @Basic
    @Column(name = "napiecie")
    public String getNapiecie() {
        return napiecie;
    }

    public void setNapiecie(String napiecie) {
        this.napiecie = napiecie;
    }

    @Basic
    @Column(name = "chlodzenie")
    public String getChlodzenie() {
        return chlodzenie;
    }

    public void setChlodzenie(String chlodzenie) {
        this.chlodzenie = chlodzenie;
    }

    @Basic
    @Column(name = "opoznienie")
    public String getOpoznienie() {
        return opoznienie;
    }

    public void setOpoznienie(String opoznienie) {
        this.opoznienie = opoznienie;
    }

    @Basic
    @Column(name = "liczba_modulow")
    public String getLiczbaModulow() {
        return liczbaModulow;
    }

    public void setLiczbaModulow(String liczbaModulow) {
        this.liczbaModulow = liczbaModulow;
    }

    @Basic
    @Column(name = "kompatybilnosc")
    public String getKompatybilnosc() {
        return kompatybilnosc;
    }

    public void setKompatybilnosc(String kompatybilnosc) {
        this.kompatybilnosc = kompatybilnosc;
    }

    @Basic
    @Column(name = "max_dlugosc_GPU")
    public String getMaxDlugoscGpu() {
        return maxDlugoscGpu;
    }

    public void setMaxDlugoscGpu(String maxDlugoscGpu) {
        this.maxDlugoscGpu = maxDlugoscGpu;
    }

    @Basic
    @Column(name = "max_wysokosc_chlodzenia_CPU")
    public String getMaxWysokoscChlodzeniaCpu() {
        return maxWysokoscChlodzeniaCpu;
    }

    public void setMaxWysokoscChlodzeniaCpu(String maxWysokoscChlodzeniaCpu) {
        this.maxWysokoscChlodzeniaCpu = maxWysokoscChlodzeniaCpu;
    }

    @Basic
    @Column(name = "waga")
    public String getWaga() {
        return waga;
    }

    public void setWaga(String waga) {
        this.waga = waga;
    }

    @Basic
    @Column(name = "poziom_halasu")
    public String getPoziomHalasu() {
        return poziomHalasu;
    }

    public void setPoziomHalasu(String poziomHalasu) {
        this.poziomHalasu = poziomHalasu;
    }

    @Basic
    @Column(name = "ilosc_wentylatorow")
    public String getIloscWentylatorow() {
        return iloscWentylatorow;
    }

    public void setIloscWentylatorow(String iloscWentylatorow) {
        this.iloscWentylatorow = iloscWentylatorow;
    }

    @Basic
    @Column(name = "sposob_montazu")
    public String getSposobMontazu() {
        return sposobMontazu;
    }

    public void setSposobMontazu(String sposobMontazu) {
        this.sposobMontazu = sposobMontazu;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Atrybuty atrybuty = (Atrybuty) o;
        return idAtrybuty == atrybuty.idAtrybuty &&
                Objects.equals(imgPath, atrybuty.imgPath) &&
                Objects.equals(chipset, atrybuty.chipset) &&
                Objects.equals(socket, atrybuty.socket) &&
                Objects.equals(liczbaRdzeni, atrybuty.liczbaRdzeni) &&
                Objects.equals(liczbaWatkow, atrybuty.liczbaWatkow) &&
                Objects.equals(czestotliwoscProcesoraMin, atrybuty.czestotliwoscProcesoraMin) &&
                Objects.equals(czestotliwoscProcesoraMax, atrybuty.czestotliwoscProcesoraMax) &&
                Objects.equals(czestotliwoscMhz, atrybuty.czestotliwoscMhz) &&
                Objects.equals(zasilanie, atrybuty.zasilanie) &&
                Objects.equals(dlugosc, atrybuty.dlugosc) &&
                Objects.equals(szerokosc, atrybuty.szerokosc) &&
                Objects.equals(wysokosc, atrybuty.wysokosc) &&
                Objects.equals(glebokosc, atrybuty.glebokosc) &&
                Objects.equals(moc, atrybuty.moc) &&
                Objects.equals(rodzaj, atrybuty.rodzaj) &&
                Objects.equals(cale, atrybuty.cale) &&
                Objects.equals(iloscRamGb, atrybuty.iloscRamGb) &&
                Objects.equals(zlacza, atrybuty.zlacza) &&
                Objects.equals(szynaDanychBit, atrybuty.szynaDanychBit) &&
                Objects.equals(interfejs, atrybuty.interfejs) &&
                Objects.equals(formatDysku, atrybuty.formatDysku) &&
                Objects.equals(pojemnoscGb, atrybuty.pojemnoscGb) &&
                Objects.equals(obroty, atrybuty.obroty) &&
                Objects.equals(szybkoscOdczytu, atrybuty.szybkoscOdczytu) &&
                Objects.equals(szybkoscZapisu, atrybuty.szybkoscZapisu) &&
                Objects.equals(standardPamieci, atrybuty.standardPamieci) &&
                Objects.equals(iloscSlotowPamieci, atrybuty.iloscSlotowPamieci) &&
                Objects.equals(czestotliwoscPamieciMax, atrybuty.czestotliwoscPamieciMax) &&
                Objects.equals(iloscPamieciMax, atrybuty.iloscPamieciMax) &&
                Objects.equals(modularneOkablowanie, atrybuty.modularneOkablowanie) &&
                Objects.equals(certyfikatSprawnosci, atrybuty.certyfikatSprawnosci) &&
                Objects.equals(napiecie, atrybuty.napiecie) &&
                Objects.equals(chlodzenie, atrybuty.chlodzenie) &&
                Objects.equals(opoznienie, atrybuty.opoznienie) &&
                Objects.equals(liczbaModulow, atrybuty.liczbaModulow) &&
                Objects.equals(kompatybilnosc, atrybuty.kompatybilnosc) &&
                Objects.equals(maxDlugoscGpu, atrybuty.maxDlugoscGpu) &&
                Objects.equals(maxWysokoscChlodzeniaCpu, atrybuty.maxWysokoscChlodzeniaCpu) &&
                Objects.equals(waga, atrybuty.waga) &&
                Objects.equals(poziomHalasu, atrybuty.poziomHalasu) &&
                Objects.equals(iloscWentylatorow, atrybuty.iloscWentylatorow) &&
                Objects.equals(sposobMontazu, atrybuty.sposobMontazu);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idAtrybuty, imgPath, chipset, socket, liczbaRdzeni, liczbaWatkow, czestotliwoscProcesoraMin, czestotliwoscProcesoraMax, czestotliwoscMhz, zasilanie, dlugosc, szerokosc, wysokosc, glebokosc, moc, rodzaj, cale, iloscRamGb, zlacza, szynaDanychBit, interfejs, formatDysku, pojemnoscGb, obroty, szybkoscOdczytu, szybkoscZapisu, standardPamieci, iloscSlotowPamieci, czestotliwoscPamieciMax, iloscPamieciMax, modularneOkablowanie, certyfikatSprawnosci, napiecie, chlodzenie, opoznienie, liczbaModulow, kompatybilnosc, maxDlugoscGpu, maxWysokoscChlodzeniaCpu, waga, poziomHalasu, iloscWentylatorow, sposobMontazu);
    }

    @Basic
    @Column(name = "Procesor")
    public String getProcesor() {
        return procesor;
    }

    public void setProcesor(String procesor) {
        this.procesor = procesor;
    }

    @Basic
    @Column(name = "Karta_graficzna")
    public String getKartaGraficzna() {
        return kartaGraficzna;
    }

    public void setKartaGraficzna(String kartaGraficzna) {
        this.kartaGraficzna = kartaGraficzna;
    }

    @Basic
    @Column(name = "System_operacyjny")
    public String getSystemOperacyjny() {
        return systemOperacyjny;
    }

    public void setSystemOperacyjny(String systemOperacyjny) {
        this.systemOperacyjny = systemOperacyjny;
    }

    @Basic
    @Column(name = "Bateria")
    public String getBateria() {
        return bateria;
    }

    public void setBateria(String bateria) {
        this.bateria = bateria;
    }

    @Basic
    @Column(name = "Zastosowanie")
    public String getZastosowanie() {
        return zastosowanie;
    }

    public void setZastosowanie(String zastosowanie) {
        this.zastosowanie = zastosowanie;
    }

    @Basic
    @Column(name = "Liczba_stanowisk")
    public String getLiczbaStanowisk() {
        return liczbaStanowisk;
    }

    public void setLiczbaStanowisk(String liczbaStanowisk) {
        this.liczbaStanowisk = liczbaStanowisk;
    }

    @Basic
    @Column(name = "Okres_licencji")
    public String getOkresLicencji() {
        return okresLicencji;
    }

    public void setOkresLicencji(String okresLicencji) {
        this.okresLicencji = okresLicencji;
    }

    @Basic
    @Column(name = "Platforma")
    public String getPlatforma() {
        return platforma;
    }

    public void setPlatforma(String platforma) {
        this.platforma = platforma;
    }

    @Basic
    @Column(name = "Sklad_pakietu")
    public String getSkladPakietu() {
        return skladPakietu;
    }

    public void setSkladPakietu(String skladPakietu) {
        this.skladPakietu = skladPakietu;
    }

    @Basic
    @Column(name = "Architektura")
    public String getArchitektura() {
        return architektura;
    }

    public void setArchitektura(String architektura) {
        this.architektura = architektura;
    }

    @Basic
    @Column(name = "Licencja")
    public String getLicencja() {
        return licencja;
    }

    public void setLicencja(String licencja) {
        this.licencja = licencja;
    }

    @Basic
    @Column(name = "Technologia_druku")
    public String getTechnologiaDruku() {
        return technologiaDruku;
    }

    public void setTechnologiaDruku(String technologiaDruku) {
        this.technologiaDruku = technologiaDruku;
    }

    @Basic
    @Column(name = "Max_format_papieru")
    public String getMaxFormatPapieru() {
        return maxFormatPapieru;
    }

    public void setMaxFormatPapieru(String maxFormatPapieru) {
        this.maxFormatPapieru = maxFormatPapieru;
    }

    @Basic
    @Column(name = "Podajnik_papieru")
    public String getPodajnikPapieru() {
        return podajnikPapieru;
    }

    public void setPodajnikPapieru(String podajnikPapieru) {
        this.podajnikPapieru = podajnikPapieru;
    }

    @Basic
    @Column(name = "Odbiornik_papieru")
    public String getOdbiornikPapieru() {
        return odbiornikPapieru;
    }

    public void setOdbiornikPapieru(String odbiornikPapieru) {
        this.odbiornikPapieru = odbiornikPapieru;
    }

    @Basic
    @Column(name = "Szybkosc_druku")
    public String getSzybkoscDruku() {
        return szybkoscDruku;
    }

    public void setSzybkoscDruku(String szybkoscDruku) {
        this.szybkoscDruku = szybkoscDruku;
    }

    @Basic
    @Column(name = "Max_rozdzielczosc_druku")
    public String getMaxRozdzielczoscDruku() {
        return maxRozdzielczoscDruku;
    }

    public void setMaxRozdzielczoscDruku(String maxRozdzielczoscDruku) {
        this.maxRozdzielczoscDruku = maxRozdzielczoscDruku;
    }

    @Basic
    @Column(name = "Lacznosc")
    public String getLacznosc() {
        return lacznosc;
    }

    public void setLacznosc(String lacznosc) {
        this.lacznosc = lacznosc;
    }

    @Basic
    @Column(name = "Rozdzielczosc")
    public String getRozdzielczosc() {
        return rozdzielczosc;
    }

    public void setRozdzielczosc(String rozdzielczosc) {
        this.rozdzielczosc = rozdzielczosc;
    }

    @Basic
    @Column(name = "Format_ekranu")
    public String getFormatEkranu() {
        return formatEkranu;
    }

    public void setFormatEkranu(String formatEkranu) {
        this.formatEkranu = formatEkranu;
    }

    @Basic
    @Column(name = "Odswiezanie_ekranu")
    public String getOdswiezanieEkranu() {
        return odswiezanieEkranu;
    }

    public void setOdswiezanieEkranu(String odswiezanieEkranu) {
        this.odswiezanieEkranu = odswiezanieEkranu;
    }

    @Basic
    @Column(name = "Matryca")
    public String getMatryca() {
        return matryca;
    }

    public void setMatryca(String matryca) {
        this.matryca = matryca;
    }

    @Basic
    @Column(name = "Dlugosc_przewodu_zasieg")
    public String getDlugoscPrzewoduZasieg() {
        return dlugoscPrzewoduZasieg;
    }

    public void setDlugoscPrzewoduZasieg(String dlugoscPrzewoduZasieg) {
        this.dlugoscPrzewoduZasieg = dlugoscPrzewoduZasieg;
    }
}
