package DataBase_AutoGenerated;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Objects;

@Entity
public class Chat {
    private int idchat;
    private String klient;
    private String pracownik;

    @Id
    @Column(name = "idchat", nullable = false)
    public int getIdchat() {
        return idchat;
    }

    public void setIdchat(int idchat) {
        this.idchat = idchat;
    }

    @Basic
    @Column(name = "klient", nullable = true, length = 200)
    public String getKlient() {
        return klient;
    }

    public void setKlient(String klient) {
        this.klient = klient;
    }

    @Basic
    @Column(name = "pracownik", nullable = true, length = 200)
    public String getPracownik() {
        return pracownik;
    }

    public void setPracownik(String pracownik) {
        this.pracownik = pracownik;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Chat chat = (Chat) o;
        return idchat == chat.idchat &&
                Objects.equals(klient, chat.klient) &&
                Objects.equals(pracownik, chat.pracownik);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idchat, klient, pracownik);
    }
}
