package DataBase_AutoGenerated;

import javax.persistence.*;
import java.util.Objects;

@Entity
public class Encja {
    private int idEncja;
    private Atrybuty atrybutyByAtrybutyIdAtrybuty;

    @Id
    @Column(name = "idEncja")
    public int getIdEncja() {
        return idEncja;
    }

    public void setIdEncja(int idEncja) {
        this.idEncja = idEncja;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Encja encja = (Encja) o;
        return idEncja == encja.idEncja;
    }

    @Override
    public int hashCode() {
        return Objects.hash(idEncja);
    }

    @ManyToOne
    @JoinColumn(name = "Atrybuty_idAtrybuty", referencedColumnName = "idAtrybuty", nullable = false)
    public Atrybuty getAtrybutyByAtrybutyIdAtrybuty() {
        return atrybutyByAtrybutyIdAtrybuty;
    }

    public void setAtrybutyByAtrybutyIdAtrybuty(Atrybuty atrybutyByAtrybutyIdAtrybuty) {
        this.atrybutyByAtrybutyIdAtrybuty = atrybutyByAtrybutyIdAtrybuty;
    }
}
