package DataBase_AutoGenerated;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Objects;

@Entity
public class Faktura {
    private int idFaktura;
    private String nazwa;
    private String cena;
    private String iloscProduktow;
    private String dataSprzedazy;
    private Integer idKlientFk;
    private String control;

    @Id
    @Column(name = "idFaktura")
    public int getIdFaktura() {
        return idFaktura;
    }

    public void setIdFaktura(int idFaktura) {
        this.idFaktura = idFaktura;
    }

    @Basic
    @Column(name = "Nazwa")
    public String getNazwa() {
        return nazwa;
    }

    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    @Basic
    @Column(name = "Cena")
    public String getCena() {
        return cena;
    }

    public void setCena(String cena) {
        this.cena = cena;
    }

    @Basic
    @Column(name = "Ilosc_produktow")
    public String getIloscProduktow() {
        return iloscProduktow;
    }

    public void setIloscProduktow(String iloscProduktow) {
        this.iloscProduktow = iloscProduktow;
    }

    @Basic
    @Column(name = "Data_sprzedazy")
    public String getDataSprzedazy() {
        return dataSprzedazy;
    }

    public void setDataSprzedazy(String dataSprzedazy) {
        this.dataSprzedazy = dataSprzedazy;
    }

    @Basic
    @Column(name = "idKlient_FK")
    public Integer getIdKlientFk() {
        return idKlientFk;
    }

    public void setIdKlientFk(Integer idKlientFk) {
        this.idKlientFk = idKlientFk;
    }

    @Basic
    @Column(name = "Control")
    public String getControl() {
        return control;
    }

    public void setControl(String control) {
        this.control = control;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Faktura faktura = (Faktura) o;
        return idFaktura == faktura.idFaktura &&
                Objects.equals(nazwa, faktura.nazwa) &&
                Objects.equals(cena, faktura.cena) &&
                Objects.equals(iloscProduktow, faktura.iloscProduktow) &&
                Objects.equals(dataSprzedazy, faktura.dataSprzedazy) &&
                Objects.equals(idKlientFk, faktura.idKlientFk) &&
                Objects.equals(control, faktura.control);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idFaktura, nazwa, cena, iloscProduktow, dataSprzedazy, idKlientFk, control);
    }
}
