package DataBase_AutoGenerated;

import javax.persistence.Column;
import javax.persistence.Id;
import java.io.Serializable;
import java.util.Objects;

public class KlientPK implements Serializable {
    private int idKlient;
    private int osobaIdOsoba;

    @Column(name = "idKlient")
    @Id
    public int getIdKlient() {
        return idKlient;
    }

    public void setIdKlient(int idKlient) {
        this.idKlient = idKlient;
    }

    @Column(name = "Osoba_idOsoba")
    @Id
    public int getOsobaIdOsoba() {
        return osobaIdOsoba;
    }

    public void setOsobaIdOsoba(int osobaIdOsoba) {
        this.osobaIdOsoba = osobaIdOsoba;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        KlientPK klientPK = (KlientPK) o;
        return idKlient == klientPK.idKlient &&
                osobaIdOsoba == klientPK.osobaIdOsoba;
    }

    @Override
    public int hashCode() {
        return Objects.hash(idKlient, osobaIdOsoba);
    }
}
