package DataBase_AutoGenerated;

import javax.persistence.*;
import java.util.Objects;

@Entity
@Table(name = "kody_rabatowe", schema = "sklepinternetowy", catalog = "")
public class KodyRabatowe {
    private int idkodyRabatowe;
    private String nazwa;
    private String rabat;
    private String rabatProcent;

    @Id
    @Column(name = "idkody_rabatowe", nullable = false)
    public int getIdkodyRabatowe() {
        return idkodyRabatowe;
    }

    public void setIdkodyRabatowe(int idkodyRabatowe) {
        this.idkodyRabatowe = idkodyRabatowe;
    }

    @Basic
    @Column(name = "nazwa", nullable = true, length = 45)
    public String getNazwa() {
        return nazwa;
    }

    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    @Basic
    @Column(name = "rabat", nullable = true, length = 45)
    public String getRabat() {
        return rabat;
    }

    public void setRabat(String rabat) {
        this.rabat = rabat;
    }

    @Basic
    @Column(name = "rabat_procent", nullable = true, length = 45)
    public String getRabatProcent() {
        return rabatProcent;
    }

    public void setRabatProcent(String rabatProcent) {
        this.rabatProcent = rabatProcent;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        KodyRabatowe that = (KodyRabatowe) o;
        return idkodyRabatowe == that.idkodyRabatowe &&
                Objects.equals(nazwa, that.nazwa) &&
                Objects.equals(rabat, that.rabat) &&
                Objects.equals(rabatProcent, that.rabatProcent);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idkodyRabatowe, nazwa, rabat, rabatProcent);
    }
}
