package DataBase_AutoGenerated;

import javax.persistence.*;
import java.util.Objects;

@Entity
@Table(name = "koszyk_zamowienie", schema = "sklepinternetowy", catalog = "")
public class KoszykZamowienie {
    private int idKoszyk;
    private int idKlientFk;
    private Integer ilosc;
    private Integer cenaKoncowa;
    private Integer cenaRabat;
    private String rabat;
    private String status;

    @Id
    @Column(name = "idKoszyk", nullable = false)
    public int getIdKoszyk() {
        return idKoszyk;
    }

    public void setIdKoszyk(int idKoszyk) {
        this.idKoszyk = idKoszyk;
    }

    @Basic
    @Column(name = "idKlient_FK", nullable = false)
    public int getIdKlientFk() {
        return idKlientFk;
    }

    public void setIdKlientFk(int idKlientFk) {
        this.idKlientFk = idKlientFk;
    }

    @Basic
    @Column(name = "Ilosc", nullable = true)
    public Integer getIlosc() {
        return ilosc;
    }

    public void setIlosc(Integer ilosc) {
        this.ilosc = ilosc;
    }

    @Basic
    @Column(name = "Cena_koncowa", nullable = true)
    public Integer getCenaKoncowa() {
        return cenaKoncowa;
    }

    public void setCenaKoncowa(Integer cenaKoncowa) {
        this.cenaKoncowa = cenaKoncowa;
    }

    @Basic
    @Column(name = "Cena_rabat", nullable = true)
    public Integer getCenaRabat() {
        return cenaRabat;
    }

    public void setCenaRabat(Integer cenaRabat) {
        this.cenaRabat = cenaRabat;
    }

    @Basic
    @Column(name = "Rabat", nullable = true, length = 45)
    public String getRabat() {
        return rabat;
    }

    public void setRabat(String rabat) {
        this.rabat = rabat;
    }

    @Basic
    @Column(name = "Status", nullable = true, length = 45)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        KoszykZamowienie that = (KoszykZamowienie) o;
        return idKoszyk == that.idKoszyk &&
                idKlientFk == that.idKlientFk &&
                Objects.equals(ilosc, that.ilosc) &&
                Objects.equals(cenaKoncowa, that.cenaKoncowa) &&
                Objects.equals(cenaRabat, that.cenaRabat) &&
                Objects.equals(rabat, that.rabat) &&
                Objects.equals(status, that.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idKoszyk, idKlientFk, ilosc, cenaKoncowa, cenaRabat, rabat, status);
    }
}
