package DataBase_AutoGenerated;

import javax.persistence.*;
import java.util.Objects;

@Entity
@Table(name = "koszyk_produkty", schema = "sklepinternetowy", catalog = "")
public class KoszykProdukty {
    private int idkoszykProdukty;
    private int idKoszykFk;
    private int idProduktyFk;

    @Id
    @Column(name = "idkoszyk_produkty")
    public int getIdkoszykProdukty() {
        return idkoszykProdukty;
    }

    public void setIdkoszykProdukty(int idkoszykProdukty) {
        this.idkoszykProdukty = idkoszykProdukty;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        KoszykProdukty that = (KoszykProdukty) o;
        return idkoszykProdukty == that.idkoszykProdukty;
    }

    @Override
    public int hashCode() {
        return Objects.hash(idkoszykProdukty);
    }

    @Basic
    @Column(name = "idKoszyk_FK")
    public int getIdKoszykFk() {
        return idKoszykFk;
    }

    public void setIdKoszykFk(int idKoszykFk) {
        this.idKoszykFk = idKoszykFk;
    }

    @Basic
    @Column(name = "idProdukty_FK")
    public int getIdProduktyFk() {
        return idProduktyFk;
    }

    public void setIdProduktyFk(int idProduktyFk) {
        this.idProduktyFk = idProduktyFk;
    }
}
