package DataBase_AutoGenerated;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Objects;

@Entity
public class Naprawa {
    private int idNaprawa;
    private String opis;
    private Integer data;
    private String nazwaCzesci;

    @Id
    @Column(name = "idNaprawa")
    public int getIdNaprawa() {
        return idNaprawa;
    }

    public void setIdNaprawa(int idNaprawa) {
        this.idNaprawa = idNaprawa;
    }

    @Basic
    @Column(name = "Opis")
    public String getOpis() {
        return opis;
    }

    public void setOpis(String opis) {
        this.opis = opis;
    }

    @Basic
    @Column(name = "Data")
    public Integer getData() {
        return data;
    }

    public void setData(Integer data) {
        this.data = data;
    }

    @Basic
    @Column(name = "Nazwa_czesci")
    public String getNazwaCzesci() {
        return nazwaCzesci;
    }

    public void setNazwaCzesci(String nazwaCzesci) {
        this.nazwaCzesci = nazwaCzesci;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Naprawa naprawa = (Naprawa) o;
        return idNaprawa == naprawa.idNaprawa &&
                Objects.equals(opis, naprawa.opis) &&
                Objects.equals(data, naprawa.data) &&
                Objects.equals(nazwaCzesci, naprawa.nazwaCzesci);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idNaprawa, opis, data, nazwaCzesci);
    }
}
