package DataBase_AutoGenerated;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Objects;

@Entity
public class Powiadomienia {
    private int idPowiadomienia;
    private String temat;
    private String tresc;
    private Integer od;
    private Integer idOsobaFk;

    @Id
    @Column(name = "idPowiadomienia", nullable = false)
    public int getIdPowiadomienia() {
        return idPowiadomienia;
    }

    public void setIdPowiadomienia(int idPowiadomienia) {
        this.idPowiadomienia = idPowiadomienia;
    }

    @Basic
    @Column(name = "temat", nullable = true, length = 45)
    public String getTemat() {
        return temat;
    }

    public void setTemat(String temat) {
        this.temat = temat;
    }

    @Basic
    @Column(name = "tresc", nullable = true, length = 100)
    public String getTresc() {
        return tresc;
    }

    public void setTresc(String tresc) {
        this.tresc = tresc;
    }

    @Basic
    @Column(name = "od", nullable = true)
    public Integer getOd() {
        return od;
    }

    public void setOd(Integer od) {
        this.od = od;
    }

    @Basic
    @Column(name = "idOsoba_FK", nullable = true)
    public Integer getIdOsobaFk() {
        return idOsobaFk;
    }

    public void setIdOsobaFk(Integer idOsobaFk) {
        this.idOsobaFk = idOsobaFk;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Powiadomienia that = (Powiadomienia) o;
        return idPowiadomienia == that.idPowiadomienia &&
                Objects.equals(temat, that.temat) &&
                Objects.equals(tresc, that.tresc) &&
                Objects.equals(od, that.od) &&
                Objects.equals(idOsobaFk, that.idOsobaFk);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idPowiadomienia, temat, tresc, od, idOsobaFk);
    }
}
