package DataBase_AutoGenerated;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Objects;

@Entity
public class Pracownik {
    private int idPracownik;
    private String stanowisko;
    private Integer pensja;
    private Integer premia;
    private Integer przepracowaneGodz;
    private int osobaIdOsoba;

    @Id
    @Column(name = "idPracownik", nullable = false)
    public int getIdPracownik() {
        return idPracownik;
    }

    public void setIdPracownik(int idPracownik) {
        this.idPracownik = idPracownik;
    }

    @Basic
    @Column(name = "Stanowisko", nullable = true, length = 45)
    public String getStanowisko() {
        return stanowisko;
    }

    public void setStanowisko(String stanowisko) {
        this.stanowisko = stanowisko;
    }

    @Basic
    @Column(name = "Pensja", nullable = true)
    public Integer getPensja() {
        return pensja;
    }

    public void setPensja(Integer pensja) {
        this.pensja = pensja;
    }

    @Basic
    @Column(name = "Premia", nullable = true)
    public Integer getPremia() {
        return premia;
    }

    public void setPremia(Integer premia) {
        this.premia = premia;
    }

    @Basic
    @Column(name = "PrzepracowaneGodz", nullable = true)
    public Integer getPrzepracowaneGodz() {
        return przepracowaneGodz;
    }

    public void setPrzepracowaneGodz(Integer przepracowaneGodz) {
        this.przepracowaneGodz = przepracowaneGodz;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Pracownik pracownik = (Pracownik) o;
        return idPracownik == pracownik.idPracownik &&
                Objects.equals(stanowisko, pracownik.stanowisko) &&
                Objects.equals(pensja, pracownik.pensja) &&
                Objects.equals(premia, pracownik.premia) &&
                Objects.equals(przepracowaneGodz, pracownik.przepracowaneGodz);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idPracownik, stanowisko, pensja, premia, przepracowaneGodz);
    }

    @Basic
    @Column(name = "Osoba_idOsoba", nullable = false)
    public int getOsobaIdOsoba() {
        return osobaIdOsoba;
    }

    public void setOsobaIdOsoba(int osobaIdOsoba) {
        this.osobaIdOsoba = osobaIdOsoba;
    }
}
