package DataBase_AutoGenerated;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Objects;

@Entity
public class Produkty {
    private int idProdukty;
    private String kategoria;
    private String nazwa;
    private Integer cena;
    private String producent;

    @Id
    @Column(name = "idProdukty")
    public int getIdProdukty() {
        return idProdukty;
    }

    public void setIdProdukty(int idProdukty) {
        this.idProdukty = idProdukty;
    }

    @Basic
    @Column(name = "Kategoria")
    public String getKategoria() {
        return kategoria;
    }

    public void setKategoria(String kategoria) {
        this.kategoria = kategoria;
    }

    @Basic
    @Column(name = "Nazwa")
    public String getNazwa() {
        return nazwa;
    }

    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    @Basic
    @Column(name = "Cena")
    public Integer getCena() {
        return cena;
    }

    public void setCena(Integer cena) {
        this.cena = cena;
    }

    @Basic
    @Column(name = "Producent")
    public String getProducent() {
        return producent;
    }

    public void setProducent(String producent) {
        this.producent = producent;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Produkty produkty = (Produkty) o;
        return idProdukty == produkty.idProdukty &&
                Objects.equals(kategoria, produkty.kategoria) &&
                Objects.equals(nazwa, produkty.nazwa) &&
                Objects.equals(cena, produkty.cena) &&
                Objects.equals(producent, produkty.producent);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idProdukty, kategoria, nazwa, cena, producent);
    }
}
