package DataBase_AutoGenerated;

import javax.persistence.*;
import java.util.Objects;

@Entity
@Table(name = "user_groups", schema = "sklepinternetowy", catalog = "")
@IdClass(UserGroupsPK.class)
public class UserGroups {
    private int idOsoba;
    private int groupId;

    @Id
    @Column(name = "idOsoba")
    public int getIdOsoba() {
        return idOsoba;
    }

    public void setIdOsoba(int idOsoba) {
        this.idOsoba = idOsoba;
    }

    @Id
    @Column(name = "group_id")
    public int getGroupId() {
        return groupId;
    }

    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        UserGroups that = (UserGroups) o;
        return idOsoba == that.idOsoba &&
                groupId == that.groupId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(idOsoba, groupId);
    }
}
