package DataBase_AutoGenerated;

import javax.persistence.*;
import java.util.Objects;

@Entity
@Table(name = "zamowienia_magazyn", schema = "sklepinternetowy", catalog = "")
public class ZamowieniaMagazyn {
    private int idZamowieniaMagazyn;
    private String dataZłożenia;
    private String dataRealizacji;
    private String nazwaZamowienia;
    private String status;

    @Id
    @Column(name = "idZamowienia_magazyn")
    public int getIdZamowieniaMagazyn() {
        return idZamowieniaMagazyn;
    }

    public void setIdZamowieniaMagazyn(int idZamowieniaMagazyn) {
        this.idZamowieniaMagazyn = idZamowieniaMagazyn;
    }

    @Basic
    @Column(name = "Data_złożenia")
    public String getDataZłożenia() {
        return dataZłożenia;
    }

    public void setDataZłożenia(String dataZłożenia) {
        this.dataZłożenia = dataZłożenia;
    }

    @Basic
    @Column(name = "Data_realizacji")
    public String getDataRealizacji() {
        return dataRealizacji;
    }

    public void setDataRealizacji(String dataRealizacji) {
        this.dataRealizacji = dataRealizacji;
    }

    @Basic
    @Column(name = "Nazwa_zamowienia")
    public String getNazwaZamowienia() {
        return nazwaZamowienia;
    }

    public void setNazwaZamowienia(String nazwaZamowienia) {
        this.nazwaZamowienia = nazwaZamowienia;
    }

    @Basic
    @Column(name = "Status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ZamowieniaMagazyn that = (ZamowieniaMagazyn) o;
        return idZamowieniaMagazyn == that.idZamowieniaMagazyn &&
                Objects.equals(dataZłożenia, that.dataZłożenia) &&
                Objects.equals(dataRealizacji, that.dataRealizacji) &&
                Objects.equals(nazwaZamowienia, that.nazwaZamowienia) &&
                Objects.equals(status, that.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idZamowieniaMagazyn, dataZłożenia, dataRealizacji, nazwaZamowienia, status);
    }
}
