package warstwa_Controller.Strona_User;

import DataBase_AutoGenerated.Chat;
import warstwa_Model.Strona_User.ChatUserDAO;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import java.io.IOException;
import java.util.List;

@ManagedBean
@RequestScoped
public class ChatUser {

    private List<Chat> chatList;
    private String text_user;


    @EJB
    ChatUserDAO chatUserDAO;


    /**
     * Metoda inicjująca
     */
    @PostConstruct
    public void init(){
        chatList = chatUserDAO.loadAllChat();
    }

    /**
     * Metoda wczytująca chat
     */
    public void loadChat(){
        FacesContext context = FacesContext.getCurrentInstance();
        try {
            context.getExternalContext().redirect("/_User/ChatUser.xhtml");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    /** Test */ public String loadChat___TEST(){
        return "/_User/ChatUser.xhtml";
    }

    /**
     * Metoda odpowiedzialna za dodawanie nowych wiadomości
     */
    public void addText(){
        chatUserDAO.dodajTextUser(getText_user());
        init();
    }

    /**
     * Gettery i Settery
     * @return
     */
    /*************************/
    public String getText_user() {
        return text_user;
    }

    public void setText_user(String text_user) {
        this.text_user = text_user;
    }

    public List<Chat> getChatList() {
        return chatList;
    }

    public void setChatList(List<Chat> chatList) {
        this.chatList = chatList;
    }
    /*************************/
}
