package warstwa_Controller.Strona_User;

import DataBase_AutoGenerated.Osoba;
import warstwa_Model.Strona_User.ProfilDAO;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import java.io.IOException;
import java.security.MessageDigest;
import java.util.List;

import static java.lang.Integer.parseInt;

@ManagedBean
@SessionScoped
public class Profil {

    private List<Osoba> listaProfil;
    private String imie;
    private String nazwisko;
    private String login;
    private String haslo;
    private String email;
    private String miasto;
    private String ulica;
    private String nrDomu;
    private String kodPocztowy;


    @EJB
    ProfilDAO profilDAO;

    /**
     * Zwraca id klienta który jest aktualnie zalogowany
     *
     * @return
     */
    /** Baza */public String getCurrentUserIDByUsername() {
        String currentUsername = FacesContext.getCurrentInstance().getExternalContext().getRemoteUser();
        return String.valueOf(profilDAO.getCurrentUserID(currentUsername)).replace("[", "").replace("]", "");

    }


    public void openEdycjaPrfilu() {

        int idOsoba = parseInt((String.valueOf(profilDAO.getCurrentOsobaID(parseInt(getCurrentUserIDByUsername())))).replace("[", "").replace("]", ""));


        listaProfil = profilDAO.getListOfClients(idOsoba);
        FacesContext context = FacesContext.getCurrentInstance();
        try {
            context.getExternalContext().redirect("/_User/ProfilUser.xhtml");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Metoda konwertująca na SHA256
     * @param data
     * @return
     */
    public static String getSHA256(String data){
        StringBuilder sb = new StringBuilder();
        try{
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(data.getBytes());
            byte[] byteData = md.digest();

            for (byte byteDatum : byteData) {
                sb.append(Integer.toString((byteDatum & 0xff) + 0x100, 16).substring(1));
            }
        } catch(Exception e){
            e.printStackTrace();
        }
        return sb.toString();
    }

    public void SaveClient(){

        int idOsoba = parseInt((String.valueOf(profilDAO.getCurrentOsobaID(parseInt(getCurrentUserIDByUsername())))).replace("[", "").replace("]", ""));

        profilDAO.updateClients(idOsoba, login, getSHA256(haslo), imie, nazwisko, email, miasto, ulica, nrDomu, kodPocztowy);

        listaProfil.clear();
        openEdycjaPrfilu();
    }

    public List<Osoba> getlistaProfil() {
        return listaProfil;
    }

    public void setlistaProfil(List<Osoba> listaProfil) {
        this.listaProfil = listaProfil;
    }

    public String getImie() {
        return imie;
    }

    public void setImie(String imie) {
        this.imie = imie;
    }

    public String getNazwisko() {
        return nazwisko;
    }

    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getHaslo() {
        return haslo;
    }

    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMiasto() {
        return miasto;
    }

    public void setMiasto(String miasto) {
        this.miasto = miasto;
    }

    public String getUlica() {
        return ulica;
    }

    public void setUlica(String ulica) {
        this.ulica = ulica;
    }

    public String getNrDomu() {
        return nrDomu;
    }

    public void setNrDomu(String nrDomu) {
        this.nrDomu = nrDomu;
    }

    public String getKodPocztowy() {
        return kodPocztowy;
    }

    public void setKodPocztowy(String kodPocztowy) {
        this.kodPocztowy = kodPocztowy;
    }
}
