package warstwa_Controller.Strona_Admin;

import DataBase_AutoGenerated.ZamowieniaMagazyn;
import warstwa_Model.Strona_Admin.ZamowieniaDAO;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import java.io.IOException;
import java.util.List;

@ManagedBean
@SessionScoped
/**
 * Klasa odpowiedzialna za kontrolowanie zamówień
 * w zakładce admina
 */
public class AdminZamowienia {

    private List<ZamowieniaMagazyn> listaZamowienia;
    private int id = 1;
    private int idCheck = 0;


    @EJB
    private ZamowieniaDAO zamowieniaDAO;


    /**
     * Metoda inicjalizujaca liste zamówień z warstwy modelu
     */
    @PostConstruct
    public void init() {
        listaZamowienia = zamowieniaDAO.getListOfOrders(id);
        idCheck = zamowieniaDAO.getIdOfOrders().size();
    }

    /**
     * Metoda zwiekszajaca indeks listy o 1 po nacisnieciu przycisku
     */
    /** Baza */ public void nextID(){

        listaZamowienia = zamowieniaDAO.getListOfOrders(id);

        if(id == idCheck){
            id=1;
        }else{
            id++;
        }
    }

    /**
     * Metoda przekierowujaca użytkownika do kolejnej strony
     */
    public void loadFiles(){

        FacesContext context = FacesContext.getCurrentInstance();
        try {
            context.getExternalContext().redirect("/_Admin/Order.xhtml");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    /** Test */ public String loadFiles___TEST(){
        return "/_Admin/Order.xhtml";
    }

    /**
     * Gettery i Settery
     * @return
     */
    /*************************/
    public List<ZamowieniaMagazyn> getListaZamowienia() {
        return listaZamowienia;
    }
    /*************************/
}
