package warstwa_Model.Strona_Employee;


import DataBase_AutoGenerated.Chat;

import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import java.util.List;

@Stateless
@LocalBean
public class ChatEmployeeDAO {


    @PersistenceContext
    private EntityManager entityManager;


    /**
     * Dodaje nowy tekst do bazy
     * @param test_employee
     */
    public void dodajTextUser(String test_employee) {

        Chat chat = new Chat();
        chat.setPracownik(test_employee);
        entityManager.persist(chat);
    }

    /**
     * Zwraca wiadomości z chatu
     * @return
     */
    public List<Chat> loadAllChat() {
        return entityManager.createQuery("SELECT c FROM Chat c", Chat.class).getResultList();
    }
}
