package warstwa_Model.Strona_Employee;


import DataBase_AutoGenerated.KodyRabatowe;

import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import java.util.List;

@Stateless
@LocalBean
public class KodRabatowyDAO {


    @PersistenceContext
    private EntityManager entityManager;


    /**
     * Dodaje nowy kod rabatowy
     * @param Nazwa
     * @param Rabat
     * @param RabatProcent
     */
    public void addKodRabatowy(String Nazwa, String Rabat, String RabatProcent){
        KodyRabatowe kodRabatowy = new KodyRabatowe();
        kodRabatowy.setNazwa(Nazwa);
        kodRabatowy.setRabat(Rabat);
        kodRabatowy.setRabatProcent(RabatProcent);
        entityManager.persist(kodRabatowy);
    }

    /**
     * Usuwa kod rabatowy
     * @param id_kodu_rabatowego_ktory_chcemy_usunac
     */
    public void deleteKodRabatowy(int id_kodu_rabatowego_ktory_chcemy_usunac){
        entityManager.createNativeQuery("DELETE FROM kody_rabatowe WHERE idkody_rabatowe ="+ id_kodu_rabatowego_ktory_chcemy_usunac).executeUpdate();
    }

    /**
     * Zwraca liste kodów rabatowych
     * @return
     */
    public List<Object[]> listaKodowRabatowych() {
        return entityManager.createNativeQuery("SELECT * FROM kody_rabatowe").getResultList();
    }

}
