package warstwa_Model.Strona_Admin;

import DataBase_AutoGenerated.ZamowieniaMagazyn;

import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import java.util.List;

@Stateless
@LocalBean
/**
 * Klasa pobierajaca dane z bazy danych
 * dla list zamówień
 */
public class ZamowieniaDAO {


    @PersistenceContext
    private EntityManager entityManager;


    /**
     * Metoda pobierajaca liste Zamówienia
     * @param i numer zamówienia
     * @return liste zamówień
     */
    public List<ZamowieniaMagazyn> getListOfOrders(int i) {
        return entityManager.createQuery("SELECT z FROM ZamowieniaMagazyn z WHERE z.idZamowieniaMagazyn =" + i, ZamowieniaMagazyn.class).getResultList();
    }

    /**
     * Metoda pobierająca id zamówienia
     * @return zwraca wartosc id jako string
     */
    public List<String> getIdOfOrders(){
        Query query = entityManager.createNativeQuery("SELECT idZamowienia_magazyn FROM zamowienia_magazyn");
        List list =  query.getResultList();

        return list;
    }
}
