package warstwa_Model.Strona_User;


import DataBase_AutoGenerated.Chat;

import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import java.util.List;

@Stateless
@LocalBean
public class ChatUserDAO {


    @PersistenceContext
    private EntityManager entityManager;


    /**
     * Dodaje nowy tekst do bazy
     * @param text_user
     */
    public void dodajTextUser(String text_user) {

        Chat chat = new Chat();
        chat.setKlient(text_user);
        entityManager.persist(chat);
    }

    /**
     * Zwraca wiadomości z chatu
     * @return
     */
    public List<Chat> loadAllChat() {
        return entityManager.createQuery("SELECT c FROM Chat c", Chat.class).getResultList();
    }
}
