package warstwa_Model.Strona_User;

import DataBase_AutoGenerated.Osoba;

import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import java.util.List;

@Stateless
@LocalBean
public class ProfilDAO {

    @PersistenceContext
    private EntityManager entityManager;

    public List<Osoba> getListOfClients(int i) {
        return entityManager.createQuery("SELECT o FROM Osoba o WHERE o.idOsoba =" + i, Osoba.class).getResultList();
    }

    /**
     * Zwraca bieżące ID użytkownika
     * @param currentUsername
     * @return
     */
    public List getCurrentUserID(String currentUsername){
        return entityManager.createNativeQuery("SELECT k.idKlient FROM klient k, osoba o WHERE o.idOsoba = k.Osoba_idOsoba AND o.Login = '" + currentUsername + "'").getResultList();
    }

    /**
     * Metoda zwraca aktualne ID osoby zalogowanej
     * @param currentIDklient
     * @return
     */
    public List getCurrentOsobaID(int currentIDklient){
        return entityManager.createNativeQuery("SELECT k.Osoba_idOsoba FROM klient k WHERE k.idKlient =" + currentIDklient).getResultList();
    }

    public void updateClients(int id, String login, String haslo, String imie, String nazwisko, String email, String miasto, String ulica, String nrDomu, String kodPocztowy){
        entityManager.createNativeQuery("UPDATE Osoba SET Login = '" + login + "'," + " Haslo = '" + haslo + "'," + " Imie = '" + imie + "'," + " Nazwisko = '" + nazwisko + "'," + " Email = '" + email +"'," + " Miasto = '" + miasto +"'," + " Ulica = '" + ulica +"'," + " NrDomu = '" + nrDomu +"'," + " KodPocztowy = '" + kodPocztowy + "' WHERE idOsoba = " + id).executeUpdate();
    }
}
